version: '3'

services:

  postgres:
    build: ./postgres
    container_name: wake_postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgres/data

  react:
    build: ./react
    container_name: wake_react
    ports:
      - "3000:3000"

  django:
    build: ./django
    container_name: wake_django
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://user:user@wake_db:5432/wake_db
    ports:
      - "8000:8000"
