version: '3'

services:
  db:
    build: ./postgres
    container_name: wake_postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/db/data:/var/l    ib/postgresql/data

  django:
    build: ./django
    container_name: wake_django
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydb
    ports:
      - "8000:8000"
    depends_on:
      - db

  react:
    build: ./react
    container_name: wake_react
    ports:
      - "3000:3000"
    depends_on:
      - django