# Use an official PostgreSQL image as a base
FROM postgres:latest

# Set the environment variables
ENV POSTGRES_USER=user
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=mydb

# Expose the port
EXPOSE 5432